require 'active_support/core_ext/class/attribute_accessors'

module CzPayrollee5
  class ConceptCode
    cattr_reader :CONCEPT_UNKNOWN
    cattr_reader :CONCEPT_EMPLOYMENT_TERM
    cattr_reader :CONCEPT_AGREEMENT_WORK_TERM
    cattr_reader :CONCEPT_AGREEMENT_TASK_TERM
    cattr_reader :CONCEPT_POSITION_TERM
    cattr_reader :CONCEPT_SCHEDULE_WEEKLY
    cattr_reader :CONCEPT_SALARY_MONTHLY
    cattr_reader :CONCEPT_TIMESHEET_SCHEDULE
    cattr_reader :CONCEPT_TIMESHEET_WORKING
    cattr_reader :CONCEPT_TIMESHEET_ABSENCE
    cattr_reader :CONCEPT_HOURS_WORKING
    cattr_reader :CONCEPT_HOURS_ABSENCE
    cattr_reader :CONCEPT_INSURANCE_HEALTH_BASE
    cattr_reader :CONCEPT_INSURANCE_HEALTH
    cattr_reader :CONCEPT_INSURANCE_SOCIAL_BASE
    cattr_reader :CONCEPT_INSURANCE_SOCIAL
    cattr_reader :CONCEPT_SAVING_PENSION_BASE
    cattr_reader :CONCEPT_SAVING_PENSION
    cattr_reader :CONCEPT_TAX_INCOME
    cattr_reader :CONCEPT_TAX_INCOME_ADVANCE
    cattr_reader :CONCEPT_TAX_INCOME_WITHHOLD
    cattr_reader :CONCEPT_TAX_CLAIM_PAYER
    cattr_reader :CONCEPT_TAX_CLAIM_CHILD
    cattr_reader :CONCEPT_TAX_CLAIM_DISABILITY
    cattr_reader :CONCEPT_TAX_CLAIM_STUDYING
    cattr_reader :CONCEPT_TAX_RELIEF_PAYER
    cattr_reader :CONCEPT_TAX_RELIEF_CHILD
    cattr_reader :CONCEPT_TAX_BONUS_CHILD
    cattr_reader :CONCEPT_TAX_ADVANCE_HEALTH
    cattr_reader :CONCEPT_TAX_ADVANCE_SOCIAL
    cattr_reader :CONCEPT_TAX_ADVANCE_PART
    cattr_reader :CONCEPT_TAX_ADVANCE_BASE
    cattr_reader :CONCEPT_TAX_SOLIDARY_BASE
    cattr_reader :CONCEPT_TAX_ADVANCE
    cattr_reader :CONCEPT_TAX_SOLIDARY
    cattr_reader :CONCEPT_TAX_ADVANCE_FINAL
    cattr_reader :CONCEPT_TAX_WITHHOLD_HEALTH
    cattr_reader :CONCEPT_TAX_WITHHOLD_SOCIAL
    cattr_reader :CONCEPT_TAX_WITHHOLD_PART
    cattr_reader :CONCEPT_TAX_WITHHOLD_BASE
    cattr_reader :CONCEPT_TAX_WITHHOLD
    cattr_reader :CONCEPT_INCOME_GROSS
    cattr_reader :CONCEPT_INCOME_NETTO

    @@CONCEPT_UNKNOWN                = 0
    @@CONCEPT_EMPLOYMENT_TERM        = 10201
    @@CONCEPT_AGREEMENT_WORK_TERM    = 10301
    @@CONCEPT_AGREEMENT_TASK_TERM    = 10401
    @@CONCEPT_POSITION_TERM          = 11001
    @@CONCEPT_SCHEDULE_WEEKLY        = 20101
    @@CONCEPT_SALARY_MONTHLY         = 20201
    @@CONCEPT_TIMESHEET_SCHEDULE     = 20301
    @@CONCEPT_TIMESHEET_WORKING      = 20401
    @@CONCEPT_TIMESHEET_ABSENCE      = 20501
    @@CONCEPT_HOURS_WORKING          = 20601
    @@CONCEPT_HOURS_ABSENCE          = 20701
    @@CONCEPT_INSURANCE_HEALTH_BASE  = 30101
    @@CONCEPT_INSURANCE_HEALTH       = 30201
    @@CONCEPT_INSURANCE_SOCIAL_BASE  = 30301
    @@CONCEPT_INSURANCE_SOCIAL       = 30401
    @@CONCEPT_SAVING_PENSION_BASE    = 30501
    @@CONCEPT_SAVING_PENSION         = 30601
    @@CONCEPT_TAX_INCOME             = 40101
    @@CONCEPT_TAX_INCOME_ADVANCE     = 40201
    @@CONCEPT_TAX_INCOME_WITHHOLD    = 40301
    @@CONCEPT_TAX_CLAIM_PAYER        = 41101
    @@CONCEPT_TAX_CLAIM_CHILD        = 41201
    @@CONCEPT_TAX_CLAIM_DISABILITY   = 41301
    @@CONCEPT_TAX_CLAIM_STUDYING     = 41401
    @@CONCEPT_TAX_RELIEF_PAYER       = 42101
    @@CONCEPT_TAX_RELIEF_CHILD       = 42201
    @@CONCEPT_TAX_BONUS_CHILD        = 42301
    @@CONCEPT_TAX_ADVANCE_HEALTH     = 43101
    @@CONCEPT_TAX_ADVANCE_SOCIAL     = 43201
    @@CONCEPT_TAX_ADVANCE_PART       = 43301
    @@CONCEPT_TAX_ADVANCE_BASE       = 43401
    @@CONCEPT_TAX_SOLIDARY_BASE      = 43501
    @@CONCEPT_TAX_ADVANCE            = 43601
    @@CONCEPT_TAX_SOLIDARY           = 43701
    @@CONCEPT_TAX_ADVANCE_FINAL      = 43801
    @@CONCEPT_TAX_WITHHOLD_HEALTH    = 44101
    @@CONCEPT_TAX_WITHHOLD_SOCIAL    = 44201
    @@CONCEPT_TAX_WITHHOLD_PART      = 44301
    @@CONCEPT_TAX_WITHHOLD_BASE      = 44401
    @@CONCEPT_TAX_WITHHOLD           = 44501
    @@CONCEPT_INCOME_GROSS           = 50101
    @@CONCEPT_INCOME_NETTO           = 50201
  end
end

