require 'active_support/core_ext/class/attribute_accessors'

module CzPayrollee5
  class ConceptCode
    CONCEPT_UNKNOWN                = 0
    CONCEPT_EMPLOYMENT_TERM        = 10201
    CONCEPT_AGREEMENT_WORK_TERM    = 10301
    CONCEPT_AGREEMENT_TASK_TERM    = 10401
    CONCEPT_POSITION_TERM          = 11001
    CONCEPT_SCHEDULE_WEEKLY        = 20101
    CONCEPT_SALARY_MONTHLY         = 20201
    CONCEPT_TIMESHEET_SCHEDULE     = 20301
    CONCEPT_TIMESHEET_WORKING      = 20401
    CONCEPT_TIMESHEET_ABSENCE      = 20501
    CONCEPT_HOURS_WORKING          = 20601
    CONCEPT_HOURS_ABSENCE          = 20701
    CONCEPT_SUBJECTS_INS_HEALTH    = 30101
    CONCEPT_SUBJECTS_INS_SOCIAL    = 30201
    CONCEPT_SUBJECTS_SAV_PENSION   = 30301
    CONCEPT_SUBJECTS_TAX           = 30401
    CONCEPT_SUBJECTS_TAX_ADVANCE   = 30501
    CONCEPT_SUBJECTS_TAX_WITHHOLD  = 30601
    CONCEPT_INSURANCE_HEALTH_BASE  = 31101
    CONCEPT_INSURANCE_HEALTH       = 31201
    CONCEPT_INSURANCE_SOCIAL_BASE  = 31301
    CONCEPT_INSURANCE_SOCIAL       = 31401
    CONCEPT_SAVINGS_PENSION_BASE   = 31501
    CONCEPT_SAVINGS_PENSION        = 31601
    CONCEPT_TAX_STATEMENT          = 40101
    CONCEPT_TAX_CLAIM_PAYER        = 41101
    CONCEPT_TAX_CLAIM_CHILD        = 41201
    CONCEPT_TAX_CLAIM_DISABILITY   = 41301
    CONCEPT_TAX_CLAIM_STUDYING     = 41401
    CONCEPT_TAX_RELIEF_PAYER       = 42101
    CONCEPT_TAX_RELIEF_CHILD       = 42201
    CONCEPT_TAX_BONUS_CHILD        = 42301
    CONCEPT_TAX_ADVANCE_HEALTH     = 43101
    CONCEPT_TAX_ADVANCE_SOCIAL     = 43201
    CONCEPT_TAX_ADVANCE_PART       = 43301
    CONCEPT_TAX_ADVANCE_BASE       = 43401
    CONCEPT_TAX_SOLIDARY_BASE      = 43501
    CONCEPT_TAX_ADVANCE            = 43601
    CONCEPT_TAX_SOLIDARY           = 43701
    CONCEPT_TAX_ADVANCE_FINAL      = 43801
    CONCEPT_TAX_WITHHOLD_HEALTH    = 44101
    CONCEPT_TAX_WITHHOLD_SOCIAL    = 44201
    CONCEPT_TAX_WITHHOLD_PART      = 44301
    CONCEPT_TAX_WITHHOLD_BASE      = 44401
    CONCEPT_TAX_WITHHOLD           = 44501
    CONCEPT_INCOME_GROSS           = 50101
    CONCEPT_INCOME_NETTO           = 50201

    def self.to_s(number_value)
      case number_value
        when ConceptCode::CONCEPT_UNKNOWN
          :CONCEPT_UNKNOWN.id2name
        when ConceptCode::CONCEPT_EMPLOYMENT_TERM
          :CONCEPT_EMPLOYMENT_TERM.id2name
        when ConceptCode::CONCEPT_AGREEMENT_WORK_TERM
          :CONCEPT_AGREEMENT_WORK_TERM.id2name
        when ConceptCode::CONCEPT_AGREEMENT_TASK_TERM
          :CONCEPT_AGREEMENT_TASK_TERM.id2name
        when ConceptCode::CONCEPT_POSITION_TERM
          :CONCEPT_POSITION_TERM.id2name
        when ConceptCode::CONCEPT_SCHEDULE_WEEKLY
          :CONCEPT_SCHEDULE_WEEKLY.id2name
        when ConceptCode::CONCEPT_SALARY_MONTHLY
          :CONCEPT_SALARY_MONTHLY.id2name
        when ConceptCode::CONCEPT_TIMESHEET_SCHEDULE
          :CONCEPT_TIMESHEET_SCHEDULE.id2name
        when ConceptCode::CONCEPT_TIMESHEET_WORKING
          :CONCEPT_TIMESHEET_WORKING.id2name
        when ConceptCode::CONCEPT_TIMESHEET_ABSENCE
          :CONCEPT_TIMESHEET_ABSENCE.id2name
        when ConceptCode::CONCEPT_HOURS_WORKING
          :CONCEPT_HOURS_WORKING.id2name
        when ConceptCode::CONCEPT_HOURS_ABSENCE
          :CONCEPT_HOURS_ABSENCE.id2name
        when ConceptCode::CONCEPT_SUBJECTS_INS_HEALTH
          :CONCEPT_SUBJECTS_INS_HEALTH.id2name
        when ConceptCode::CONCEPT_SUBJECTS_INS_SOCIAL
          :CONCEPT_SUBJECTS_INS_SOCIAL.id2name
        when ConceptCode::CONCEPT_SUBJECTS_SAV_PENSION
          :CONCEPT_SUBJECTS_SAV_PENSION.id2name
        when ConceptCode::CONCEPT_SUBJECTS_TAX
          :CONCEPT_SUBJECTS_TAX.id2name
        when ConceptCode::CONCEPT_SUBJECTS_TAX_ADVANCE
          :CONCEPT_SUBJECTS_TAX_ADVANCE.id2name
        when ConceptCode::CONCEPT_SUBJECTS_TAX_WITHHOLD
          :CONCEPT_SUBJECTS_TAX_WITHHOLD.id2name
        when ConceptCode::CONCEPT_INSURANCE_HEALTH_BASE
          :CONCEPT_INSURANCE_HEALTH_BASE.id2name
        when ConceptCode::CONCEPT_INSURANCE_HEALTH
          :CONCEPT_INSURANCE_HEALTH.id2name
        when ConceptCode::CONCEPT_INSURANCE_SOCIAL_BASE
          :CONCEPT_INSURANCE_SOCIAL_BASE.id2name
        when ConceptCode::CONCEPT_INSURANCE_SOCIAL
          :CONCEPT_INSURANCE_SOCIAL.id2name
        when ConceptCode::CONCEPT_SAVINGS_PENSION_BASE
          :CONCEPT_SAVINGS_PENSION_BASE.id2name
        when ConceptCode::CONCEPT_SAVINGS_PENSION
          :CONCEPT_SAVINGS_PENSION.id2name
        when ConceptCode::CONCEPT_TAX_STATEMENT
          :CONCEPT_TAX_STATEMENT.id2name
        when ConceptCode::CONCEPT_TAX_CLAIM_PAYER
          :CONCEPT_TAX_CLAIM_PAYER.id2name
        when ConceptCode::CONCEPT_TAX_CLAIM_CHILD
          :CONCEPT_TAX_CLAIM_CHILD.id2name
        when ConceptCode::CONCEPT_TAX_CLAIM_DISABILITY
          :CONCEPT_TAX_CLAIM_DISABILITY.id2name
        when ConceptCode::CONCEPT_TAX_CLAIM_STUDYING
          :CONCEPT_TAX_CLAIM_STUDYING.id2name
        when ConceptCode::CONCEPT_TAX_RELIEF_PAYER
          :CONCEPT_TAX_RELIEF_PAYER.id2name
        when ConceptCode::CONCEPT_TAX_RELIEF_CHILD
          :CONCEPT_TAX_RELIEF_CHILD.id2name
        when ConceptCode::CONCEPT_TAX_BONUS_CHILD
          :CONCEPT_TAX_BONUS_CHILD.id2name
        when ConceptCode::CONCEPT_TAX_ADVANCE_HEALTH
          :CONCEPT_TAX_ADVANCE_HEALTH.id2name
        when ConceptCode::CONCEPT_TAX_ADVANCE_SOCIAL
          :CONCEPT_TAX_ADVANCE_SOCIAL.id2name
        when ConceptCode::CONCEPT_TAX_ADVANCE_PART
          :CONCEPT_TAX_ADVANCE_PART.id2name
        when ConceptCode::CONCEPT_TAX_ADVANCE_BASE
          :CONCEPT_TAX_ADVANCE_BASE.id2name
        when ConceptCode::CONCEPT_TAX_SOLIDARY_BASE
          :CONCEPT_TAX_SOLIDARY_BASE.id2name
        when ConceptCode::CONCEPT_TAX_ADVANCE
          :CONCEPT_TAX_ADVANCE.id2name
        when ConceptCode::CONCEPT_TAX_SOLIDARY
          :CONCEPT_TAX_SOLIDARY.id2name
        when ConceptCode::CONCEPT_TAX_ADVANCE_FINAL
          :CONCEPT_TAX_ADVANCE_FINAL.id2name
        when ConceptCode::CONCEPT_TAX_WITHHOLD_HEALTH
          :CONCEPT_TAX_WITHHOLD_HEALTH.id2name
        when ConceptCode::CONCEPT_TAX_WITHHOLD_SOCIAL
          :CONCEPT_TAX_WITHHOLD_SOCIAL.id2name
        when ConceptCode::CONCEPT_TAX_WITHHOLD_PART
          :CONCEPT_TAX_WITHHOLD_PART.id2name
        when ConceptCode::CONCEPT_TAX_WITHHOLD_BASE
          :CONCEPT_TAX_WITHHOLD_BASE.id2name
        when ConceptCode::CONCEPT_TAX_WITHHOLD
          :CONCEPT_TAX_WITHHOLD.id2name
        when ConceptCode::CONCEPT_INCOME_GROSS
          :CONCEPT_INCOME_GROSS.id2name
        when ConceptCode::CONCEPT_INCOME_NETTO
          :CONCEPT_INCOME_NETTO.id2name
        else
          'unknown'
      end
    end
  end
end

